// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpcGkQPnSpgA2hQfmgLjQ8P-C_ni5j6Mo',
    appId: '1:832843490506:web:26e57e5b449d281a6c0033',
    messagingSenderId: '832843490506',
    projectId: 'glouriousart-94699',
    authDomain: 'glouriousart-94699.firebaseapp.com',
    storageBucket: 'glouriousart-94699.firebasestorage.app',
    measurementId: 'G-2F9BGR6LDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkoImdGTrb4XSYwkkHFiud4Sk9m79UD7k',
    appId: '1:832843490506:android:b81c5dfb5166cc736c0033',
    messagingSenderId: '832843490506',
    projectId: 'glouriousart-94699',
    storageBucket: 'glouriousart-94699.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBseUlTRaCZEqvQoA3HWDemyIQZYHv-WXo',
    appId: '1:832843490506:ios:cc08f0eac514f0bf6c0033',
    messagingSenderId: '832843490506',
    projectId: 'glouriousart-94699',
    storageBucket: 'glouriousart-94699.firebasestorage.app',
    androidClientId: '832843490506-3jghlkk31ushfublv0gp3g35m88je8kn.apps.googleusercontent.com',
    iosClientId: '832843490506-lct9v7oujucmhts91p1frkmdicg0paot.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBseUlTRaCZEqvQoA3HWDemyIQZYHv-WXo',
    appId: '1:832843490506:ios:cc08f0eac514f0bf6c0033',
    messagingSenderId: '832843490506',
    projectId: 'glouriousart-94699',
    storageBucket: 'glouriousart-94699.firebasestorage.app',
    androidClientId: '832843490506-3jghlkk31ushfublv0gp3g35m88je8kn.apps.googleusercontent.com',
    iosClientId: '832843490506-lct9v7oujucmhts91p1frkmdicg0paot.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpcGkQPnSpgA2hQfmgLjQ8P-C_ni5j6Mo',
    appId: '1:832843490506:web:d6d4f83b717cc1056c0033',
    messagingSenderId: '832843490506',
    projectId: 'glouriousart-94699',
    authDomain: 'glouriousart-94699.firebaseapp.com',
    storageBucket: 'glouriousart-94699.firebasestorage.app',
    measurementId: 'G-K0DQE3H5RQ',
  );
}
